[General]
description = N robots communicating wirelessly
network = WirelessNetwork
sim-time-limit = 300s
user-interface = Qtenv

*.numRobots = 2

# Logging
################################
cmdenv-express-mode = true
**.cmdenv-log-level = info
**.radio.displayReception = true
**.radio.displayTransmission = true

################################
# IP addressing
################################
*.configurator.config = xml("<config><interface hosts='**' address='10.0.0.x' netmask='255.255.255.0'/></config>")

################################
# Wireless Interface
################################
*.robot*.numWlanInterfaces = 1
*.robot*.wlan[0].typename = "Ieee80211Interface"
*.robot*.wlan[0].radio.typename = "Ieee80211ScalarRadio"
*.robot*.wlan[0].radio.bandName = "2.4 GHz"
*.robot*.wlan[0].radio.transmitter.power = 2mW
*.robot*.wlan[0].radio.receiver.sensitivity = -85dBm
*.robot*.wlan[0].radio.receiver.noiseFloor = -110dBm
*.robot*.wlan[0].radio.receiver.energyDetection = -90dBm
*.robot*.wlan[0].radio.receiver.ignoreInterference = false
*.robot*.wlan[0].radio.transmitter.communicationRange = 150m
################################
# MAC
################################
*.robot*.wlan[0].mac.typename = "Ieee80211Mac"
*.robot*.wlan[0].mac.dcf.channelAccess.typename = "Dcaf"
*.robot*.wlan[0].mac.useAck = false
*.robot*.wlan[0].mac.fullDuplex = false
*.robot*.wlan[0].mac.headerLength = 23B

################################
# Applications
################################
*.robot*.numApps = 1
*.robot*.app[0].typename = "UdpBasicApp"
*.robot*.app[0].destAddresses = "255.255.255.255"
*.robot*.app[0].destPort = 5000
*.robot*.app[0].localPort = 5000
*.robot*.app[0].messageLength = 500B
*.robot*.app[0].sendInterval = exponential(1s)
*.robot*.app[0].packetName = "UDPData"

################################
# Mobility (ALL robots)
################################
*.robot[*].mobility.initFromDisplayString = false
*.robot[*].mobility.typename = "StationaryMobility"
*.robot[0].mobility.initialX = 400m
*.robot[0].mobility.initialY = 300m
*.robot[*].mobility.initialZ = 0m
*.robot[1].mobility.initialX = 100m
*.robot[1].mobility.initialY = 200m
############################
# Visualization
################################
*.visualizer.*.mobilityVisualizer.displayPositions = true
*.visualizer.*.mobilityVisualizer.displayMovementTrails = true

*.visualizer.*.mediumVisualizer.displaySignals = true
*.visualizer.*.mediumVisualizer.displaySignalPropagation = true
*.visualizer.*.mediumVisualizer.displaySignalDepartures = true
*.visualizer.*.mediumVisualizer.displaySignalArrivals = true
*.visualizer.*.mediumVisualizer.signalShape = "ring"
*.visualizer.*.mediumVisualizer.signalPropagationAnimationSpeed = 5

*.visualizer.*.physicalLinkVisualizer.displayLinks = true
*.visualizer.*.physicalLinkVisualizer.packetFilter = "UDPData*"
*.visualizer.*.mediumVisualizer.signalColor = "red"
*.visualizer.*.mediumVisualizer.fadeOutMode = "simulationTime"
################################
# Radio Medium
################################
*.radioMedium.backgroundNoiseLevel = -110dBm
*.radioMedium.interferenceMode = "scalar"
*.radioMedium.pathLoss.typename = "LogNormalShadowing"
*.radioMedium.pathLoss.alpha = 2
################################
# Ranges
################################
**.radio.displayCommunicationRange = true
